-- Premium "Sales Report" (downloadable PDF, weekly/monthly, browsable by
-- past month) — schema + RPCs. The PDF itself is generated by the web app
-- (src/app/api/reports/sales/route.ts) from these RPCs' output; this
-- migration only adds the data this report needs plus the queries to
-- fetch it for an arbitrary calendar month (not just "the last N days",
-- which the existing sales_by_* RPCs from 0013/0024 are limited to).

-- ---------------------------------------------------------------------------
-- New columns the report references
-- ---------------------------------------------------------------------------

-- Ingredient cost per item — optional, owner-entered, powers the "menu
-- engineering matrix" (popularity vs. margin). Items without a cost are
-- simply excluded from that chart (see report_menu_engineering below).
alter table menu_items add column ingredient_cost numeric(10, 2) check (ingredient_cost is null or ingredient_cost >= 0);

-- Delivery-platform commission rates, as a percentage (e.g. 26.00 = 26%).
-- Optional — the report falls back to an industry-average estimate (26%)
-- when null, same as the sample report's own behavior.
alter table restaurants add column grabfood_commission_pct numeric(5, 2) check (grabfood_commission_pct is null or grabfood_commission_pct between 0 and 100);
alter table restaurants add column foodpanda_commission_pct numeric(5, 2) check (foodpanda_commission_pct is null or foodpanda_commission_pct between 0 and 100);

-- Which delivery platform a manual delivery order came from — only
-- meaningful when channel = 'manual_delivery_entry'. Needed to split
-- "Revenue by channel" the way the report shows it (GrabFood vs.
-- foodpanda), not just "delivery" as one bucket.
alter table orders add column delivery_platform text check (delivery_platform in ('grabfood', 'foodpanda') or delivery_platform is null);

-- create_manual_order (0011_manual_orders.sql) needs to accept the platform
-- when the channel is a delivery entry. Re-declared with the new optional
-- param — same body, one new insert column.
create or replace function create_manual_order(
  p_channel order_channel,
  p_items jsonb,
  p_note text default null,
  p_delivery_platform text default null
)
returns table (order_id uuid, access_token uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_restaurant_id uuid;
  v_table_id uuid;
  v_label text;
  v_order_id uuid;
  v_access_token uuid;
  v_item jsonb;
begin
  if my_role() is null or my_role() not in ('owner', 'cashier') then
    raise exception 'not authorized';
  end if;

  if p_channel not in ('manual_delivery_entry', 'manual_pickup_entry') then
    raise exception 'invalid channel for a manual order';
  end if;

  if p_delivery_platform is not null and p_channel <> 'manual_delivery_entry' then
    raise exception 'delivery_platform only applies to manual_delivery_entry';
  end if;

  v_restaurant_id := my_restaurant_id();
  v_label := case p_channel when 'manual_delivery_entry' then 'Delivery' else 'Takeout' end;

  select id into v_table_id
    from tables
    where restaurant_id = v_restaurant_id and is_virtual = true and label = v_label;

  if v_table_id is null then
    insert into tables (restaurant_id, label, is_virtual)
      values (v_restaurant_id, v_label, true)
      returning id into v_table_id;
  end if;

  if jsonb_array_length(p_items) = 0 then
    raise exception 'order must have at least one item';
  end if;

  insert into orders (restaurant_id, table_id, channel, note, delivery_platform)
    values (v_restaurant_id, v_table_id, p_channel, nullif(trim(p_note), ''), p_delivery_platform)
    returning id, orders.access_token into v_order_id, v_access_token;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    insert into order_items (order_id, restaurant_id, menu_item_id, quantity, unit_price_snapshot)
    select
      v_order_id,
      v_restaurant_id,
      mi.id,
      greatest((v_item ->> 'quantity')::int, 1),
      mi.price
    from menu_items mi
    where mi.id = (v_item ->> 'menu_item_id')::uuid
      and mi.restaurant_id = v_restaurant_id
      and mi.is_available = true;
  end loop;

  return query select v_order_id, v_access_token;
end;
$$;

grant execute on function create_manual_order(order_channel, jsonb, text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Report RPCs — all owner-only, restaurant-scoped, and parameterized by
-- `p_month` (any date within the target calendar month — normalized with
-- date_trunc). All read only status = 'paid' orders except the heatmap and
-- combos, which (like top_combos) count any real order as a demand signal.
-- ---------------------------------------------------------------------------

-- This month + the previous calendar month's headline numbers, plus the
-- restaurant's current table count (for the turnover-rate denominator).
create or replace function report_monthly_summary(p_month date)
returns table (
  period text,
  total_revenue numeric,
  total_orders bigint,
  days_in_period int,
  table_count int
)
language sql
security definer
stable
set search_path = public
as $$
  with bounds as (
    select date_trunc('month', p_month)::date as this_start,
           (date_trunc('month', p_month) + interval '1 month')::date as this_end,
           (date_trunc('month', p_month) - interval '1 month')::date as prev_start,
           date_trunc('month', p_month)::date as prev_end
  ),
  agg as (
    select 'this' as period,
           coalesce(sum(oi.quantity * oi.unit_price_snapshot), 0) as total_revenue,
           count(distinct o.id) as total_orders,
           (select this_end - this_start from bounds) as days_in_period
    from bounds, orders o
    join order_items oi on oi.order_id = o.id
    where o.restaurant_id = my_restaurant_id()
      and my_role() = 'owner'
      and o.status = 'paid'
      and (o.created_at at time zone 'Asia/Manila')::date >= bounds.this_start
      and (o.created_at at time zone 'Asia/Manila')::date < bounds.this_end
    union all
    select 'previous' as period,
           coalesce(sum(oi.quantity * oi.unit_price_snapshot), 0),
           count(distinct o.id),
           (select prev_end - prev_start from bounds)
    from bounds, orders o
    join order_items oi on oi.order_id = o.id
    where o.restaurant_id = my_restaurant_id()
      and my_role() = 'owner'
      and o.status = 'paid'
      and (o.created_at at time zone 'Asia/Manila')::date >= bounds.prev_start
      and (o.created_at at time zone 'Asia/Manila')::date < bounds.prev_end
  )
  select agg.period, agg.total_revenue, agg.total_orders, agg.days_in_period,
         (select count(*)::int from tables where restaurant_id = my_restaurant_id() and is_virtual = false)
  from agg;
$$;

grant execute on function report_monthly_summary(date) to authenticated;

-- One row per calendar day in the month, for the daily revenue line chart
-- and the weekly-bucket table (bucketed client-side in the PDF renderer).
create or replace function report_daily_revenue(p_month date)
returns table (day_of_month int, revenue numeric, order_count bigint)
language sql
security definer
stable
set search_path = public
as $$
  select extract(day from (o.created_at at time zone 'Asia/Manila'))::int as day_of_month,
         sum(oi.quantity * oi.unit_price_snapshot),
         count(distinct o.id)
  from orders o
  join order_items oi on oi.order_id = o.id
  where o.restaurant_id = my_restaurant_id()
    and my_role() = 'owner'
    and o.status = 'paid'
    and (o.created_at at time zone 'Asia/Manila')::date >= date_trunc('month', p_month)::date
    and (o.created_at at time zone 'Asia/Manila')::date < (date_trunc('month', p_month) + interval '1 month')::date
  group by 1
  order by 1;
$$;

grant execute on function report_daily_revenue(date) to authenticated;

-- Dine-in order volume by weekday × hour — a demand signal, so (like
-- top_combos) this counts any real order, not just paid ones.
create or replace function report_day_hour_heatmap(p_month date)
returns table (day_of_week int, hour_of_day int, order_count bigint)
language sql
security definer
stable
set search_path = public
as $$
  select extract(dow from (o.created_at at time zone 'Asia/Manila'))::int as day_of_week,
         extract(hour from (o.created_at at time zone 'Asia/Manila'))::int as hour_of_day,
         count(*)
  from orders o
  where o.restaurant_id = my_restaurant_id()
    and my_role() = 'owner'
    and o.channel = 'dine_in'
    and (o.created_at at time zone 'Asia/Manila')::date >= date_trunc('month', p_month)::date
    and (o.created_at at time zone 'Asia/Manila')::date < (date_trunc('month', p_month) + interval '1 month')::date
  group by 1, 2;
$$;

grant execute on function report_day_hour_heatmap(date) to authenticated;

-- Every item's quantity/revenue for the month, sorted best-first — the PDF
-- renderer slices the top N (best sellers) and bottom N (slowest movers)
-- from this one list.
create or replace function report_item_sales(p_month date)
returns table (item_name text, total_quantity bigint, total_revenue numeric)
language sql
security definer
stable
set search_path = public
as $$
  select mi.name,
         sum(oi.quantity),
         sum(oi.quantity * oi.unit_price_snapshot)
  from order_items oi
  join orders o on o.id = oi.order_id
  join menu_items mi on mi.id = oi.menu_item_id
  where oi.restaurant_id = my_restaurant_id()
    and my_role() = 'owner'
    and o.status = 'paid'
    and (o.created_at at time zone 'Asia/Manila')::date >= date_trunc('month', p_month)::date
    and (o.created_at at time zone 'Asia/Manila')::date < (date_trunc('month', p_month) + interval '1 month')::date
  group by mi.name
  order by sum(oi.quantity) desc;
$$;

grant execute on function report_item_sales(date) to authenticated;

create or replace function report_category_revenue(p_month date)
returns table (category_name text, revenue numeric)
language sql
security definer
stable
set search_path = public
as $$
  select coalesce(mc.name, 'Uncategorized'),
         sum(oi.quantity * oi.unit_price_snapshot)
  from order_items oi
  join orders o on o.id = oi.order_id
  join menu_items mi on mi.id = oi.menu_item_id
  left join menu_categories mc on mc.id = mi.category_id
  where oi.restaurant_id = my_restaurant_id()
    and my_role() = 'owner'
    and o.status = 'paid'
    and (o.created_at at time zone 'Asia/Manila')::date >= date_trunc('month', p_month)::date
    and (o.created_at at time zone 'Asia/Manila')::date < (date_trunc('month', p_month) + interval '1 month')::date
  group by coalesce(mc.name, 'Uncategorized')
  order by 2 desc;
$$;

grant execute on function report_category_revenue(date) to authenticated;

-- Same pairing logic as top_combos (0013_sales_analytics.sql), scoped to a
-- specific calendar month instead of a rolling N-day window.
create or replace function report_combos(p_month date, p_limit int default 5)
returns table (item_a_name text, item_b_name text, order_count bigint)
language sql
security definer
stable
set search_path = public
as $$
  select mia.name, mib.name, count(distinct a.order_id)
  from order_items a
  join order_items b on a.order_id = b.order_id and a.menu_item_id < b.menu_item_id
  join menu_items mia on mia.id = a.menu_item_id
  join menu_items mib on mib.id = b.menu_item_id
  join orders o on o.id = a.order_id
  where a.restaurant_id = my_restaurant_id()
    and my_role() = 'owner'
    and (o.created_at at time zone 'Asia/Manila')::date >= date_trunc('month', p_month)::date
    and (o.created_at at time zone 'Asia/Manila')::date < (date_trunc('month', p_month) + interval '1 month')::date
  group by mia.name, mib.name
  having count(distinct a.order_id) >= 2
  order by count(distinct a.order_id) desc
  limit p_limit;
$$;

grant execute on function report_combos(date, int) to authenticated;

-- Popularity (orders this month) × margin (%) for items that have an
-- ingredient_cost set. `total_with_cost`/`total_items` let the report show
-- "N of M items missing cost data" without a second round trip.
create or replace function report_menu_engineering(p_month date)
returns table (
  item_name text,
  quantity bigint,
  margin_pct numeric,
  total_items int,
  items_with_cost int
)
language sql
security definer
stable
set search_path = public
as $$
  with sales as (
    select oi.menu_item_id, sum(oi.quantity) as quantity
    from order_items oi
    join orders o on o.id = oi.order_id
    where oi.restaurant_id = my_restaurant_id()
      and my_role() = 'owner'
      and o.status = 'paid'
      and (o.created_at at time zone 'Asia/Manila')::date >= date_trunc('month', p_month)::date
      and (o.created_at at time zone 'Asia/Manila')::date < (date_trunc('month', p_month) + interval '1 month')::date
    group by oi.menu_item_id
  ),
  counts as (
    select count(*)::int as total_items,
           count(*) filter (where ingredient_cost is not null)::int as items_with_cost
    from menu_items
    where restaurant_id = my_restaurant_id()
  )
  select mi.name,
         coalesce(sales.quantity, 0),
         round((mi.price - mi.ingredient_cost) / nullif(mi.price, 0) * 100, 1),
         counts.total_items,
         counts.items_with_cost
  from menu_items mi
  cross join counts
  left join sales on sales.menu_item_id = mi.id
  where mi.restaurant_id = my_restaurant_id()
    and mi.ingredient_cost is not null
  order by coalesce(sales.quantity, 0) desc;
$$;

grant execute on function report_menu_engineering(date) to authenticated;

-- Gross revenue by channel — dine-in, and delivery split by platform
-- (unset delivery_platform on an older/manual order groups under
-- 'unspecified'). Commission-adjusted net is computed in the report
-- renderer using the restaurant's own commission_pct columns (or the 26%
-- estimate fallback), not here.
create or replace function report_channel_revenue(p_month date)
returns table (channel order_channel, delivery_platform text, revenue numeric)
language sql
security definer
stable
set search_path = public
as $$
  select o.channel, o.delivery_platform,
         sum(oi.quantity * oi.unit_price_snapshot)
  from orders o
  join order_items oi on oi.order_id = o.id
  where o.restaurant_id = my_restaurant_id()
    and my_role() = 'owner'
    and o.status = 'paid'
    and (o.created_at at time zone 'Asia/Manila')::date >= date_trunc('month', p_month)::date
    and (o.created_at at time zone 'Asia/Manila')::date < (date_trunc('month', p_month) + interval '1 month')::date
  group by o.channel, o.delivery_platform;
$$;

grant execute on function report_channel_revenue(date) to authenticated;
